[tool.commitizen]
tag_format = "v$version"
version_scheme = "pep440"

# Set to true to allow bumping to 0.y.z from 0.(y-1).z when commit types normally trigger major bump.
# Recommended for initial development phases before 1.0.0.
major_version_zero = true

write_version_files = [
    "pyproject.toml:version",
    "src/robust_python_demo/__init__.py:__version__",
]
commit_msg_file = ".git/COMMIT_EDITMSG"
retry_after_failure = true
update_changelog_on_bump = true

[tool.commitizen.github]
release = true
release_asset_path = "dist/*"
release_asset_descriptions = { "*.tar.gz" = "Source distribution", "*.whl" = "Python Wheel" }
base_url = "https://github.com/56kyle/robust-python-demo"
