version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

python:
  install:
    # This is required for ReadTheDocs to consider it a Python project and install dependencies.
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/conf.py
