name: Bump version

on:
  push:
    branches:
      - "release/*"

permissions:
  contents: write

jobs:
  bump-version-and-draft-release:
    name: Bump Version and Draft Release
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md

      - name: Create Release Draft
        uses: softprops/action-gh-release@v1
        with:
          body_path: body.md
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  draft-release:
    name: Draft Release
    if: "startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .github/workflows/.python-version

      - name: Get Release Notes
        run: uvx nox -s get-release-notes

      - name: Create Release Draft
        uses: softprops/action-gh-release@v1
        with:
          body_path: body.md
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
